### ISSUE TITLE
as long as ur logged in, you dont need password

### ISSUE THREAD

**Issue by TheFinality** [Ba3a-G/Check-Valorant#2]
So basically, you can send a request to the valorant server, and if u are logged in, it will work. Meaning u can use fetch() on the client side, since they are logged into the valorant website themselves.

**Comment by TheFinality** [comment]
people would probably trust this way the most, since u dont have to input anything

**Comment by Ba3a-G** [comment]
Initially we had plans to do what you are saying but their resources are protected by CORS. So, can't really do it. I am gonna mark the issue closed.
